# Generated by Django 3.2.7 on 2021-09-22 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gathered', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
